"""This file was generated by xsdata, v23.8, on 2023-10-17 11:34:35

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass, field
from pyeml_bindings.src.x_al_kiesraad_strict import AddressDetails
from pyeml_bindings.src.x_nl_kiesraad_strict import (
    NameDetails1,
    PersonName,
)

__NAMESPACE__ = "urn:oasis:names:tc:evs:schema:eml"


@dataclass(kw_only=True)
class AuthorityAddressStructure(AddressDetails):
    pass


@dataclass(kw_only=True)
class ElectoralAddressStructure(AddressDetails):
    pass


@dataclass(kw_only=True)
class MailingAddressStructure(AddressDetails):
    pass


@dataclass(kw_only=True)
class OfficialAddressStructure(AddressDetails):
    pass


@dataclass(kw_only=True)
class PersonNameStructure(NameDetails1):
    person_name: PersonName = field(
        metadata={
            "name": "PersonName",
            "type": "Element",
            "namespace": "urn:oasis:names:tc:ciq:xsdschema:xNL:2.0",
            "required": True,
        }
    )


@dataclass(kw_only=True)
class PhysicalAddressStructure(AddressDetails):
    pass


@dataclass(kw_only=True)
class PostalLocationStructure(AddressDetails):
    pass


@dataclass(kw_only=True)
class ProxyAddressStructure(AddressDetails):
    pass


@dataclass(kw_only=True)
class QualifyingAddressStructure(AddressDetails):
    pass
